name: fclash
base: core18
version: '1.0'
summary: A Linux Clash Proxy Fronted based on Clash # 79 char long summary
description: |
  A Linux Clash Proxy Fronted based on Clash. Supports subscriptions, proxies switcher, logger,
  dynamic settings, profile management, auto start with system.

grade: stable
confinement: devmode
license: GPL-3.0+

slots:
  dbus-fclash:
    interface: dbus
    bus: session
    name: cn.kingtous.fclash

parts:
  fclash:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    build-packages:
      - libappindicator3-dev
    stage-packages:
      - libappindicator3-1

apps:
  fclash:
    command: fclash
    extensions: [ flutter-stable ]
    plugs:
      - network
    slots:
      - dbus-fclash